package valueobject

import (
	"net/http"

	"github.com/GuilhermeDeOliveiraAmorim/youchoose/internal"
)

type Nationality struct {
	CountryName string `json:"country_name"`
	Flag        string `json:"flag"`
}

func NewNationality(countryName, flag string) (*Nationality, []internal.ProblemDetails) {
	validationErrors := ValidateNationality(countryName)

	if len(validationErrors) > 0 {
		return nil, validationErrors
	}

	return &Nationality{
		CountryName: countryName,
		Flag:        flag,
	}, nil
}

type Country struct {
	Name     string
	DialCode string
	Code     string
	Flag     string
}

func ValidateNationality(country string) []internal.ProblemDetails {
	var validationErrors []internal.ProblemDetails

	for _, c := range countries {
		if c.Name == country {
			return validationErrors
		}
	}

	validationErrors = append(validationErrors, internal.ProblemDetails{
		Type:   "ValidationError",
		Title:  "País inválido",
		Status: http.StatusBadRequest,
		Detail: "Por favor, forneça um país válido.",
	})

	return validationErrors
}

func NewCountries() []Country {
	return countries
}

var countries = []Country{
	{Name: "Afghanistan", DialCode: "+93", Code: "AF", Flag: "🇦🇫"},
	{Name: "Albania", DialCode: "+355", Code: "AL", Flag: "🇦🇱"},
	{Name: "Algeria", DialCode: "+213", Code: "DZ", Flag: "🇩🇿"},
	{Name: "American Samoa", DialCode: "+1684", Code: "AS", Flag: "🇦🇸"},
	{Name: "Andorra", DialCode: "+376", Code: "AD", Flag: "🇦🇩"},
	{Name: "Angola", DialCode: "+244", Code: "AO", Flag: "🇦🇴"},
	{Name: "Anguilla", DialCode: "+1264", Code: "AI", Flag: "🇦🇮"},
	{Name: "Antarctica", DialCode: "+672", Code: "AQ", Flag: "🇦🇶"},
	{Name: "Antigua and Barbuda", DialCode: "+1268", Code: "AG", Flag: "🇦🇬"},
	{Name: "Argentina", DialCode: "+54", Code: "AR", Flag: "🇦🇷"},
	{Name: "Armenia", DialCode: "+374", Code: "AM", Flag: "🇦🇲"},
	{Name: "Aruba", DialCode: "+297", Code: "AW", Flag: "🇦🇼"},
	{Name: "Australia", DialCode: "+61", Code: "AU", Flag: "🇦🇺"},
	{Name: "Austria", DialCode: "+43", Code: "AT", Flag: "🇦🇹"},
	{Name: "Azerbaijan", DialCode: "+994", Code: "AZ", Flag: "🇦🇿"},
	{Name: "Bahamas", DialCode: "+1242", Code: "BS", Flag: "🇧🇸"},
	{Name: "Bahrain", DialCode: "+973", Code: "BH", Flag: "🇧🇭"},
	{Name: "Bangladesh", DialCode: "+880", Code: "BD", Flag: "🇧🇩"},
	{Name: "Barbados", DialCode: "+1246", Code: "BB", Flag: "🇧🇧"},
	{Name: "Belarus", DialCode: "+375", Code: "BY", Flag: "🇧🇾"},
	{Name: "Belgium", DialCode: "+32", Code: "BE", Flag: "🇧🇪"},
	{Name: "Belize", DialCode: "+501", Code: "BZ", Flag: "🇧🇿"},
	{Name: "Benin", DialCode: "+229", Code: "BJ", Flag: "🇧🇯"},
	{Name: "Bermuda", DialCode: "+1441", Code: "BM", Flag: "🇧🇲"},
	{Name: "Bhutan", DialCode: "+975", Code: "BT", Flag: "🇧🇹"},
	{Name: "Bolivia, Plurinational State of", DialCode: "+591", Code: "BO", Flag: "🇧🇴"},
	{Name: "Bosnia and Herzegovina", DialCode: "+387", Code: "BA", Flag: "🇧🇦"},
	{Name: "Botswana", DialCode: "+267", Code: "BW", Flag: "🇧🇼"},
	{Name: "Brazil", DialCode: "+55", Code: "BR", Flag: "🇧🇷"},
	{Name: "Brasil", DialCode: "+55", Code: "BR", Flag: "🇧🇷"},
	{Name: "British Indian Ocean Territory", DialCode: "+246", Code: "IO", Flag: "🇮🇴"},
	{Name: "Brunei Darussalam", DialCode: "+673", Code: "BN", Flag: "🇧🇳"},
	{Name: "Bulgaria", DialCode: "+359", Code: "BG", Flag: "🇧🇬"},
	{Name: "Burkina Faso", DialCode: "+226", Code: "BF", Flag: "🇧🇫"},
	{Name: "Burundi", DialCode: "+257", Code: "BI", Flag: "🇧🇮"},
	{Name: "Cambodia", DialCode: "+855", Code: "KH", Flag: "🇰🇭"},
	{Name: "Cameroon", DialCode: "+237", Code: "CM", Flag: "🇨🇲"},
	{Name: "Canada", DialCode: "+1", Code: "CA", Flag: "🇨🇦"},
	{Name: "Cape Verde", DialCode: "+238", Code: "CV", Flag: "🇨🇻"},
	{Name: "Cayman Islands", DialCode: "+345", Code: "KY", Flag: "🇰🇾"},
	{Name: "Central African Republic", DialCode: "+236", Code: "CF", Flag: "🇨🇫"},
	{Name: "Chad", DialCode: "+235", Code: "TD", Flag: "🇹🇩"},
	{Name: "Chile", DialCode: "+56", Code: "CL", Flag: "🇨🇱"},
	{Name: "China", DialCode: "+86", Code: "CN", Flag: "🇨🇳"},
	{Name: "Christmas Island", DialCode: "+61", Code: "CX", Flag: "🇨🇽"},
	{Name: "Cocos (Keeling) Islands", DialCode: "+61", Code: "CC", Flag: "🇨🇨"},
	{Name: "Colombia", DialCode: "+57", Code: "CO", Flag: "🇨🇴"},
	{Name: "Comoros", DialCode: "+269", Code: "KM", Flag: "🇰🇲"},
	{Name: "Congo", DialCode: "+242", Code: "CG", Flag: "🇨🇬"},
	{Name: "Congo, The Democratic Republic of the", DialCode: "+243", Code: "CD", Flag: "🇨🇩"},
	{Name: "Cook Islands", DialCode: "+682", Code: "CK", Flag: "🇨🇰"},
	{Name: "Costa Rica", DialCode: "+506", Code: "CR", Flag: "🇨🇷"},
	{Name: "Cote d'Ivoire", DialCode: "+225", Code: "CI", Flag: "🇨🇮"},
	{Name: "Croatia", DialCode: "+385", Code: "HR", Flag: "🇭🇷"},
	{Name: "Cuba", DialCode: "+53", Code: "CU", Flag: "🇨🇺"},
	{Name: "Cyprus", DialCode: "+357", Code: "CY", Flag: "🇨🇾"},
	{Name: "Czech Republic", DialCode: "+420", Code: "CZ", Flag: "🇨🇿"},
	{Name: "Denmark", DialCode: "+45", Code: "DK", Flag: "🇩🇰"},
	{Name: "Djibouti", DialCode: "+253", Code: "DJ", Flag: "🇩🇯"},
	{Name: "Dominica", DialCode: "+1767", Code: "DM", Flag: "🇩🇲"},
	{Name: "Dominican Republic", DialCode: "+1849", Code: "DO", Flag: "🇩🇴"},
	{Name: "Ecuador", DialCode: "+593", Code: "EC", Flag: "🇪🇨"},
	{Name: "Egypt", DialCode: "+20", Code: "EG", Flag: "🇪🇬"},
	{Name: "El Salvador", DialCode: "+503", Code: "SV", Flag: "🇸🇻"},
	{Name: "Equatorial Guinea", DialCode: "+240", Code: "GQ", Flag: "🇬🇶"},
	{Name: "Eritrea", DialCode: "+291", Code: "ER", Flag: "🇪🇷"},
	{Name: "Estonia", DialCode: "+372", Code: "EE", Flag: "🇪🇪"},
	{Name: "Ethiopia", DialCode: "+251", Code: "ET", Flag: "🇪🇹"},
	{Name: "Falkland Islands (Malvinas)", DialCode: "+500", Code: "FK", Flag: "🇫🇰"},
	{Name: "Faroe Islands", DialCode: "+298", Code: "FO", Flag: "🇫🇴"},
	{Name: "Fiji", DialCode: "+679", Code: "FJ", Flag: "🇫🇯"},
	{Name: "Finland", DialCode: "+358", Code: "FI", Flag: "🇫🇮"},
	{Name: "France", DialCode: "+33", Code: "FR", Flag: "🇫🇷"},
	{Name: "French Guiana", DialCode: "+594", Code: "GF", Flag: "🇬🇫"},
	{Name: "French Polynesia", DialCode: "+689", Code: "PF", Flag: "🇵🇫"},
	{Name: "Gabon", DialCode: "+241", Code: "GA", Flag: "🇬🇦"},
	{Name: "Gambia", DialCode: "+220", Code: "GM", Flag: "🇬🇲"},
	{Name: "Georgia", DialCode: "+995", Code: "GE", Flag: "🇬🇪"},
	{Name: "Germany", DialCode: "+49", Code: "DE", Flag: "🇩🇪"},
	{Name: "Ghana", DialCode: "+233", Code: "GH", Flag: "🇬🇭"},
	{Name: "Gibraltar", DialCode: "+350", Code: "GI", Flag: "🇬🇮"},
	{Name: "Greece", DialCode: "+30", Code: "GR", Flag: "🇬🇷"},
	{Name: "Greenland", DialCode: "+299", Code: "GL", Flag: "🇬🇱"},
	{Name: "Grenada", DialCode: "+1473", Code: "GD", Flag: "🇬🇩"},
	{Name: "Guadeloupe", DialCode: "+590", Code: "GP", Flag: "🇬🇵"},
	{Name: "Guam", DialCode: "+1671", Code: "GU", Flag: "🇬🇺"},
	{Name: "Guatemala", DialCode: "+502", Code: "GT", Flag: "🇬🇹"},
	{Name: "Guernsey", DialCode: "+44", Code: "GG", Flag: "🇬🇬"},
	{Name: "Guinea", DialCode: "+224", Code: "GN", Flag: "🇬🇳"},
	{Name: "Guinea-Bissau", DialCode: "+245", Code: "GW", Flag: "🇬🇼"},
	{Name: "Guyana", DialCode: "+592", Code: "GY", Flag: "🇬🇾"},
	{Name: "Haiti", DialCode: "+509", Code: "HT", Flag: "🇭🇹"},
	{Name: "Holy See (Vatican City State)", DialCode: "+379", Code: "VA", Flag: "🇻🇦"},
	{Name: "Honduras", DialCode: "+504", Code: "HN", Flag: "🇭🇳"},
	{Name: "Hong Kong", DialCode: "+852", Code: "HK", Flag: "🇭🇰"},
	{Name: "Hungary", DialCode: "+36", Code: "HU", Flag: "🇭🇺"},
	{Name: "Iceland", DialCode: "+354", Code: "IS", Flag: "🇮🇸"},
	{Name: "India", DialCode: "+91", Code: "IN", Flag: "🇮🇳"},
	{Name: "Indonesia", DialCode: "+62", Code: "ID", Flag: "🇮🇩"},
	{Name: "Iran, Islamic Republic of", DialCode: "+98", Code: "IR", Flag: "🇮🇷"},
	{Name: "Iraq", DialCode: "+964", Code: "IQ", Flag: "🇮🇶"},
	{Name: "Ireland", DialCode: "+353", Code: "IE", Flag: "🇮🇪"},
	{Name: "Isle of Man", DialCode: "+44", Code: "IM", Flag: "🇮🇲"},
	{Name: "Israel", DialCode: "+972", Code: "IL", Flag: "🇮🇱"},
	{Name: "Italy", DialCode: "+39", Code: "IT", Flag: "🇮🇹"},
	{Name: "Jamaica", DialCode: "+1876", Code: "JM", Flag: "🇯🇲"},
	{Name: "Japan", DialCode: "+81", Code: "JP", Flag: "🇯🇵"},
	{Name: "Jersey", DialCode: "+44", Code: "JE", Flag: "🇯🇪"},
	{Name: "Jordan", DialCode: "+962", Code: "JO", Flag: "🇯🇴"},
	{Name: "Kazakhstan", DialCode: "+77", Code: "KZ", Flag: "🇰🇿"},
	{Name: "Kenya", DialCode: "+254", Code: "KE", Flag: "🇰🇪"},
	{Name: "Kiribati", DialCode: "+686", Code: "KI", Flag: "🇰🇮"},
	{Name: "Korea, Democratic People's Republic of", DialCode: "+850", Code: "KP", Flag: "🇰🇵"},
	{Name: "Korea, Republic of", DialCode: "+82", Code: "KR", Flag: "🇰🇷"},
	{Name: "Kuwait", DialCode: "+965", Code: "KW", Flag: "🇰🇼"},
	{Name: "Kyrgyzstan", DialCode: "+996", Code: "KG", Flag: "🇰🇬"},
	{Name: "Lao People's Democratic Republic", DialCode: "+856", Code: "LA", Flag: "🇱🇦"},
	{Name: "Latvia", DialCode: "+371", Code: "LV", Flag: "🇱🇻"},
	{Name: "Lebanon", DialCode: "+961", Code: "LB", Flag: "🇱🇧"},
	{Name: "Lesotho", DialCode: "+266", Code: "LS", Flag: "🇱🇸"},
	{Name: "Liberia", DialCode: "+231", Code: "LR", Flag: "🇱🇷"},
	{Name: "Libyan Arab Jamahiriya", DialCode: "+218", Code: "LY", Flag: "🇱🇾"},
	{Name: "Liechtenstein", DialCode: "+423", Code: "LI", Flag: "🇱🇮"},
	{Name: "Lithuania", DialCode: "+370", Code: "LT", Flag: "🇱🇹"},
	{Name: "Luxembourg", DialCode: "+352", Code: "LU", Flag: "🇱🇺"},
	{Name: "Macao", DialCode: "+853", Code: "MO", Flag: "🇲🇴"},
	{Name: "Macedonia, The Former Yugoslav Republic of", DialCode: "+389", Code: "MK", Flag: "🇲🇰"},
	{Name: "Madagascar", DialCode: "+261", Code: "MG", Flag: "🇲🇬"},
	{Name: "Malawi", DialCode: "+265", Code: "MW", Flag: "🇲🇼"},
	{Name: "Malaysia", DialCode: "+60", Code: "MY", Flag: "🇲🇾"},
	{Name: "Maldives", DialCode: "+960", Code: "MV", Flag: "🇲🇻"},
	{Name: "Mali", DialCode: "+223", Code: "ML", Flag: "🇲🇱"},
	{Name: "Malta", DialCode: "+356", Code: "MT", Flag: "🇲🇹"},
	{Name: "Marshall Islands", DialCode: "+692", Code: "MH", Flag: "🇲🇭"},
	{Name: "Martinique", DialCode: "+596", Code: "MQ", Flag: "🇲🇶"},
	{Name: "Mauritania", DialCode: "+222", Code: "MR", Flag: "🇲🇷"},
	{Name: "Mauritius", DialCode: "+230", Code: "MU", Flag: "🇲🇺"},
	{Name: "Mayotte", DialCode: "+262", Code: "YT", Flag: "🇾🇹"},
	{Name: "Mexico", DialCode: "+52", Code: "MX", Flag: "🇲🇽"},
	{Name: "Micronesia, Federated States of", DialCode: "+691", Code: "FM", Flag: "🇫🇲"},
	{Name: "Moldova, Republic of", DialCode: "+373", Code: "MD", Flag: "🇲🇩"},
	{Name: "Monaco", DialCode: "+377", Code: "MC", Flag: "🇲🇨"},
	{Name: "Mongolia", DialCode: "+976", Code: "MN", Flag: "🇲🇳"},
	{Name: "Montenegro", DialCode: "+382", Code: "ME", Flag: "🇲🇪"},
	{Name: "Montserrat", DialCode: "+1664", Code: "MS", Flag: "🇲🇸"},
	{Name: "Morocco", DialCode: "+212", Code: "MA", Flag: "🇲🇦"},
	{Name: "Mozambique", DialCode: "+258", Code: "MZ", Flag: "🇲🇿"},
	{Name: "Myanmar", DialCode: "+95", Code: "MM", Flag: "🇲🇲"},
	{Name: "Namibia", DialCode: "+264", Code: "NA", Flag: "🇳🇦"},
	{Name: "Nauru", DialCode: "+674", Code: "NR", Flag: "🇳🇷"},
	{Name: "Nepal", DialCode: "+977", Code: "NP", Flag: "🇳🇵"},
	{Name: "Netherlands", DialCode: "+31", Code: "NL", Flag: "🇳🇱"},
	{Name: "Netherlands Antilles", DialCode: "+599", Code: "AN", Flag: "🇦🇳"},
	{Name: "New Caledonia", DialCode: "+687", Code: "NC", Flag: "🇳🇨"},
	{Name: "New Zealand", DialCode: "+64", Code: "NZ", Flag: "🇳🇿"},
	{Name: "Nicaragua", DialCode: "+505", Code: "NI", Flag: "🇳🇮"},
	{Name: "Niger", DialCode: "+227", Code: "NE", Flag: "🇳🇪"},
	{Name: "Nigeria", DialCode: "+234", Code: "NG", Flag: "🇳🇬"},
	{Name: "Niue", DialCode: "+683", Code: "NU", Flag: "🇳🇺"},
	{Name: "Norfolk Island", DialCode: "+672", Code: "NF", Flag: "🇳🇫"},
	{Name: "Northern Mariana Islands", DialCode: "+1670", Code: "MP", Flag: "🇲🇵"},
	{Name: "Norway", DialCode: "+47", Code: "NO", Flag: "🇳🇴"},
	{Name: "Oman", DialCode: "+968", Code: "OM", Flag: "🇴🇲"},
	{Name: "Pakistan", DialCode: "+92", Code: "PK", Flag: "🇵🇰"},
	{Name: "Palau", DialCode: "+680", Code: "PW", Flag: "🇵🇼"},
	{Name: "Palestinian Territory, Occupied", DialCode: "+970", Code: "PS", Flag: "🇵🇸"},
	{Name: "Panama", DialCode: "+507", Code: "PA", Flag: "🇵🇦"},
	{Name: "Papua New Guinea", DialCode: "+675", Code: "PG", Flag: "🇵🇬"},
	{Name: "Paraguay", DialCode: "+595", Code: "PY", Flag: "🇵🇾"},
	{Name: "Peru", DialCode: "+51", Code: "PE", Flag: "🇵🇪"},
	{Name: "Philippines", DialCode: "+63", Code: "PH", Flag: "🇵🇭"},
	{Name: "Pitcairn", DialCode: "+872", Code: "PN", Flag: "🇵🇳"},
	{Name: "Poland", DialCode: "+48", Code: "PL", Flag: "🇵🇱"},
	{Name: "Portugal", DialCode: "+351", Code: "PT", Flag: "🇵🇹"},
	{Name: "Puerto Rico", DialCode: "+1939", Code: "PR", Flag: "🇵🇷"},
	{Name: "Qatar", DialCode: "+974", Code: "QA", Flag: "🇶🇦"},
	{Name: "Romania", DialCode: "+40", Code: "RO", Flag: "🇷🇴"},
	{Name: "Russia", DialCode: "+7", Code: "RU", Flag: "🇷🇺"},
	{Name: "Rwanda", DialCode: "+250", Code: "RW", Flag: "🇷🇼"},
	{Name: "Réunion", DialCode: "+262", Code: "RE", Flag: "🇷🇪"},
	{Name: "Saint Barthélemy", DialCode: "+590", Code: "BL", Flag: "🇧🇱"},
	{Name: "Saint Helena, Ascension and Tristan Da Cunha", DialCode: "+290", Code: "SH", Flag: "🇸🇭"},
	{Name: "Saint Kitts and Nevis", DialCode: "+1869", Code: "KN", Flag: "🇰🇳"},
	{Name: "Saint Lucia", DialCode: "+1758", Code: "LC", Flag: "🇱🇨"},
	{Name: "Saint Martin", DialCode: "+590", Code: "MF", Flag: "🇲🇫"},
	{Name: "Saint Pierre and Miquelon", DialCode: "+508", Code: "PM", Flag: "🇵🇲"},
	{Name: "Saint Vincent and the Grenadines", DialCode: "+1784", Code: "VC", Flag: "🇻🇨"},
	{Name: "Samoa", DialCode: "+685", Code: "WS", Flag: "🇼🇸"},
	{Name: "San Marino", DialCode: "+378", Code: "SM", Flag: "🇸🇲"},
	{Name: "Sao Tome and Principe", DialCode: "+239", Code: "ST", Flag: "🇸🇹"},
	{Name: "Saudi Arabia", DialCode: "+966", Code: "SA", Flag: "🇸🇦"},
	{Name: "Senegal", DialCode: "+221", Code: "SN", Flag: "🇸🇳"},
	{Name: "Serbia", DialCode: "+381", Code: "RS", Flag: "🇷🇸"},
	{Name: "Seychelles", DialCode: "+248", Code: "SC", Flag: "🇸🇨"},
	{Name: "Sierra Leone", DialCode: "+232", Code: "SL", Flag: "🇸🇱"},
	{Name: "Singapore", DialCode: "+65", Code: "SG", Flag: "🇸🇬"},
	{Name: "Slovakia", DialCode: "+421", Code: "SK", Flag: "🇸🇰"},
	{Name: "Slovenia", DialCode: "+386", Code: "SI", Flag: "🇸🇮"},
	{Name: "Solomon Islands", DialCode: "+677", Code: "SB", Flag: "🇸🇧"},
	{Name: "Somalia", DialCode: "+252", Code: "SO", Flag: "🇸🇴"},
	{Name: "South Africa", DialCode: "+27", Code: "ZA", Flag: "🇿🇦"},
	{Name: "South Georgia and the South Sandwich Islands", DialCode: "+500", Code: "GS", Flag: "🇬🇸"},
	{Name: "Spain", DialCode: "+34", Code: "ES", Flag: "🇪🇸"},
	{Name: "Sri Lanka", DialCode: "+94", Code: "LK", Flag: "🇱🇰"},
	{Name: "Sudan", DialCode: "+249", Code: "SD", Flag: "🇸🇩"},
	{Name: "South Sudan", DialCode: "+211", Code: "SS", Flag: "🇸🇸"},
	{Name: "Suriname", DialCode: "+597", Code: "SR", Flag: "🇸🇷"},
	{Name: "Svalbard and Jan Mayen", DialCode: "+47", Code: "SJ", Flag: "🇸🇯"},
	{Name: "Swaziland", DialCode: "+268", Code: "SZ", Flag: "🇸🇿"},
	{Name: "Sweden", DialCode: "+46", Code: "SE", Flag: "🇸🇪"},
	{Name: "Switzerland", DialCode: "+41", Code: "CH", Flag: "🇨🇭"},
	{Name: "Syrian Arab Republic", DialCode: "+963", Code: "SY", Flag: "🇸🇾"},
	{Name: "Taiwan, Province of China", DialCode: "+886", Code: "TW", Flag: "🇹🇼"},
	{Name: "Tajikistan", DialCode: "+992", Code: "TJ", Flag: "🇹🇯"},
	{Name: "Tanzania, United Republic of", DialCode: "+255", Code: "TZ", Flag: "🇹🇿"},
	{Name: "Thailand", DialCode: "+66", Code: "TH", Flag: "🇹🇭"},
	{Name: "Timor-Leste", DialCode: "+670", Code: "TL", Flag: "🇹🇱"},
	{Name: "Togo", DialCode: "+228", Code: "TG", Flag: "🇹🇬"},
	{Name: "Tokelau", DialCode: "+690", Code: "TK", Flag: "🇹🇰"},
	{Name: "Tonga", DialCode: "+676", Code: "TO", Flag: "🇹🇴"},
	{Name: "Trinidad and Tobago", DialCode: "+1868", Code: "TT", Flag: "🇹🇹"},
	{Name: "Tunisia", DialCode: "+216", Code: "TN", Flag: "🇹🇳"},
	{Name: "Turkey", DialCode: "+90", Code: "TR", Flag: "🇹🇷"},
	{Name: "Turkmenistan", DialCode: "+993", Code: "TM", Flag: "🇹🇲"},
	{Name: "Turks and Caicos Islands", DialCode: "+1649", Code: "TC", Flag: "🇹🇨"},
	{Name: "Tuvalu", DialCode: "+688", Code: "TV", Flag: "🇹🇻"},
	{Name: "Uganda", DialCode: "+256", Code: "UG", Flag: "🇺🇬"},
	{Name: "Ukraine", DialCode: "+380", Code: "UA", Flag: "🇺🇦"},
	{Name: "United Arab Emirates", DialCode: "+971", Code: "AE", Flag: "🇦🇪"},
	{Name: "United Kingdom", DialCode: "+44", Code: "GB", Flag: "🇬🇧"},
	{Name: "United States", DialCode: "+1", Code: "US", Flag: "🇺🇸"},
	{Name: "Uruguay", DialCode: "+598", Code: "UY", Flag: "🇺🇾"},
	{Name: "Uzbekistan", DialCode: "+998", Code: "UZ", Flag: "🇺🇿"},
	{Name: "Vanuatu", DialCode: "+678", Code: "VU", Flag: "🇻🇺"},
	{Name: "Venezuela, Bolivarian Republic of", DialCode: "+58", Code: "VE", Flag: "🇻🇪"},
	{Name: "Viet Nam", DialCode: "+84", Code: "VN", Flag: "🇻🇳"},
	{Name: "Virgin Islands, British", DialCode: "+1284", Code: "VG", Flag: "🇻🇬"},
	{Name: "Virgin Islands, U.S.", DialCode: "+1340", Code: "VI", Flag: "🇻🇮"},
	{Name: "Wallis and Futuna", DialCode: "+681", Code: "WF", Flag: "🇼🇫"},
	{Name: "Yemen", DialCode: "+967", Code: "YE", Flag: "🇾🇪"},
	{Name: "Zambia", DialCode: "+260", Code: "ZM", Flag: "🇿🇲"},
	{Name: "Zimbabwe", DialCode: "+263", Code: "ZW", Flag: "🇿🇼"},
	{Name: "Åland Islands", DialCode: "+358", Code: "AX", Flag: "🇦🇽"},
}